import React from "react";
import renderer from "react-test-renderer";
import GenresList from "./genres-list";

// const films = [
//   {title: `Fantastic Beasts: The Crimes of Grindelwald`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Comedies`,
//     releaseDate: 2020,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 0,
//   },
//   {title: `Bohemian Rhapsody`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Drama`,
//     releaseDate: 2020,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 1,
//   },
//   {title: `Macbeth Aviator`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Drama`,
//     releaseDate: 2011,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 2,
//   },
//   {title: `We need to talk about Kevin`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``], genre: `Documentary`,
//     releaseDate: 2020,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 13,
//   },
//   {title: `What We Do in the Shadows Revenant`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Horror`,
//     releaseDate: 2020,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 14,
//   },
//   {title: `Johnny English`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Romance`,
//     releaseDate: 2020,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 15,
//   },
//   {title: `Pulp Fiction`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Sci-Fi`,
//     releaseDate: 1988,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 16,
//   },
//   {title: `No Country for Old Men`,
//     src: `img/bohemian-rhapsody.jpg`,
//     poster: `img/the-grand-budapest-hotel-poster.jpg`,
//     ratingScore: 5,
//     ratingCount: 100,
//     director: ` `,
//     starring: [``, ``],
//     genre: `Kids & Family`,
//     releaseDate: 1999,
//     pictureBackground: `img/bg-the-grand-budapest-hotel.jpg`,
//     previewVideo: `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
//     duration: 100,
//     backgroundColor: ``,
//     videoLink: ``,
//     description: ` `,
//     isFavorite: false,
//     id: 17,
//   }
// ];

const activeGenre = `All genre`;


it(`Should GenresList render correctly`, () => {
  const tree = renderer
    .create(<GenresList
      genresList={[activeGenre]}
      activeGenre={activeGenre}
      onGenreItemClick={() => {}}
    />
    ).toJSON();

  expect(tree).toMatchSnapshot();
});
